### PR TITLE
mktemp fix for osx shell

### PR DESCRIPTION
**Pull request by zapion**
see issue #56

### CODE REVIEW

**Comment by zapion** [comment]
@askeing r?

**Comment by askeing** [comment]
It works fine on Shing's Linux and my Mac.
I don't think the template is required in osx, and it's not a temp folder.
We just create a temp file for storing the grep result, testing it by if condition, then remove it.
Is this command failed on your Mac?

**Comment by zapion** [comment]
yes
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin14)
Copyright (C) 2007 Free Software Foundation, Inc.
The fix is not for creating a folder, if so it needs to add '-d'
see http://unix.stackexchange.com/questions/30091/fix-or-alternative-for-mktemp-in-os-x

**Comment by askeing** [comment]
The `mktemp` work on different Mac.
What's your error message and OS X version?

``` bash
Askeings-MacBook-Pro:MozITP Askeing$ bash --version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin15)
Copyright (C) 2007 Free Software Foundation, Inc.
Askeings-MacBook-Pro:MozITP Askeing$ mktemp
/var/folders/jn/b4ps9y1x5dn243rdlk2v0c2h0000gn/T/tmp.EwXQqyaR
Askeings-MacBook-Pro:MozITP Askeing$ 
```

and

```
teriwen@29992-twen:~$ bash --version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin15)
Copyright (C) 2007 Free Software Foundation, Inc.
teriwen@29992-twen:~$ mktemp
/var/folders/05/5xcwv3791bx2mkd1dms08_l00000gn/T/tmp.fvIxyr8e
teriwen@29992-twen:~$
```

**Comment by askeing** [comment]
After checking the `man mktemp`(10.11) and [mktemp](https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man1/mktemp.1.html) (10.9), there are `If no arguments are passed or if only the -d flag is passed mktemp behaves as if -t tmp was supplied.` in the 10.11's description.
I will follow the rule to add the arguments for fixing it.

**Comment by zapion** [comment]
Wondering why not just merge #57 ...

**Pull request closed without merging**
